// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
//
// NOTE: hand-written to match Pigeon's expected Swift output for this
// package's version (see pigeons/gfmc_api.dart's header comment) -- no
// Dart/Flutter SDK was available to actually run `dart run pigeon` in the
// environment that authored this. Regenerate and diff before trusting this
// for anything beyond a starting point.

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Mirrors com.sltr.gfmc.GfmcSDKEnv / JessicaSDK.JessicaEnvironment.
enum GfmcEnvMessage: Int {
  case production = 0
  case sandbox = 1
  case dev = 2
}

/// Mirrors com.sltr.gfmc.GfmcSDKTheme / JessicaSDK.JessicaTheme.
enum GfmcThemeMessage: Int {
  case dark = 0
  case light = 1
  case auto = 2
}

/// Mirrors com.sltr.gfmc.GfmcSDKError. Superset of JessicaSDK.JessicaSDKError
/// on iOS -- see pigeons/gfmc_api.dart's comment on this enum.
enum GfmcErrorMessage: Int {
  case authFailed = 0
  case networkError = 1
  case sessionExpired = 2
  case sdkNotInitialized = 3
  case webviewUnavailable = 4
  case webviewOutdated = 5
  case webviewRendererGone = 6
  case billingUnavailable = 7
  case purchaseFailed = 8
  case verifyFailed = 9
}

/// Mirrors com.sltr.gfmc.GfmcModule / JessicaSDK.JessicaModule.
enum GfmcModuleMessage: Int {
  case cinema = 0
  case game = 1
  case shop = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct GfmcConfigMessage {
  var environment: GfmcEnvMessage = .production
  var locale: String = "en"
  var theme: GfmcThemeMessage = .auto
  var enableLogging: Bool = false
  var connectionTimeoutMs: Int64 = 10000

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GfmcConfigMessage? {
    let environment = pigeonVar_list[0] as! GfmcEnvMessage
    let locale = pigeonVar_list[1] as! String
    let theme = pigeonVar_list[2] as! GfmcThemeMessage
    let enableLogging = pigeonVar_list[3] as! Bool
    let connectionTimeoutMs = pigeonVar_list[4] as! Int64

    return GfmcConfigMessage(
      environment: environment,
      locale: locale,
      theme: theme,
      enableLogging: enableLogging,
      connectionTimeoutMs: connectionTimeoutMs
    )
  }
  func toList() -> [Any?] {
    return [
      environment,
      locale,
      theme,
      enableLogging,
      connectionTimeoutMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GfmcVersionMessage {
  /// Internal SDK semantic version, e.g. "2.3.6". NOT what a host app
  /// should show a partner -- see `artifactVersion`.
  var name: String
  var versionCode: Int64
  /// The Maven coordinate this plugin's Android dependency actually pins,
  /// e.g. "1.2.6" -- what GfmcSDK.getArtifactVersion()/GET_APP_VERSION report
  /// on the native side (on iOS: JessicaSDKVersion.packageVersion, the pinned
  /// XCFramework release). This is the number to show or log.
  var artifactVersion: String
  var displayName: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GfmcVersionMessage? {
    let name = pigeonVar_list[0] as! String
    let versionCode = pigeonVar_list[1] as! Int64
    let artifactVersion = pigeonVar_list[2] as! String
    let displayName = pigeonVar_list[3] as! String

    return GfmcVersionMessage(
      name: name,
      versionCode: versionCode,
      artifactVersion: artifactVersion,
      displayName: displayName
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      versionCode,
      artifactVersion,
      displayName,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GfmcEnvMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GfmcThemeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GfmcErrorMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GfmcModuleMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return GfmcConfigMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return GfmcVersionMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GfmcEnvMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? GfmcThemeMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? GfmcErrorMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? GfmcModuleMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? GfmcConfigMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? GfmcVersionMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GfmcHostApi {
  /// Must be called once before `open`. Safe to call again to change config
  /// (e.g. switching environment) as long as no hub is currently open.
  func `init`(config: GfmcConfigMessage) throws
  /// Opens the hub with a minicinema session JWT obtained from your own
  /// backend -- NOT your app's own auth access token. Requires `init` first
  /// and a token refresher registered on the Dart side (see
  /// GfmcFlutterApi.refreshToken) if you expect long sessions.
  func open(jwt: String) throws
  /// Native-side "close" -- same effect as the user tapping the capsule's
  /// close button. No-op if no hub is currently open.
  func closeMiniApp() throws
  func getVersion() throws -> GfmcVersionMessage
  /// Null if `init` hasn't been called yet.
  func getConfig() throws -> GfmcConfigMessage?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GfmcHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `GfmcHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GfmcHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.isEmpty ? "" : ".\(messageChannelSuffix)"
    let initChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.init\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! GfmcConfigMessage
        do {
          try api.`init`(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initChannel.setMessageHandler(nil)
    }
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jwtArg = args[0] as! String
        do {
          try api.open(jwt: jwtArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let closeMiniAppChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.closeMiniApp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeMiniAppChannel.setMessageHandler { _, reply in
        do {
          try api.closeMiniApp()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeMiniAppChannel.setMessageHandler(nil)
    }
    let getVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVersionChannel.setMessageHandler(nil)
    }
    let getConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConfigChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getConfig()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getConfigChannel.setMessageHandler(nil)
    }
  }
}

/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class GfmcFlutterApi {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.isEmpty ? "" : ".\(messageChannelSuffix)"
  }
  var codec: FlutterStandardMessageCodec {
    return MessagesPigeonCodec.shared
  }
  func onHubReady(completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubReady\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onHubClosed(completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(code codeArg: GfmcErrorMessage, message messageArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPurchaseCompleted(sku skuArg: String, txId txIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseCompleted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([skuArg, txIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPurchaseFailed(reason reasonArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseFailed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([reasonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onModuleChanged(module moduleArg: GfmcModuleMessage, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onModuleChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([moduleArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onShareRequested(url urlArg: String, title titleArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onShareRequested\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([urlArg, titleArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Informational only -- does not gate the Google Play billing flow, which
  /// runs natively regardless of what this returns.
  func onSkuSelected(sku skuArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onSkuSelected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([skuArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Native asks Dart for a fresh minicinema JWT when the current one
  /// expires. Implement this to call your own backend and return the new
  /// token; throw (or let the Future fail) to signal a refresh failure --
  /// the native side maps that to the same "refresh failed" outcome as
  /// GfmcTokenRefresher.fail(reason) on the Android side.
  func refreshToken(completion: @escaping (Result<String, FlutterError>) -> Void) {
    let channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.refreshToken\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        completion(.failure(FlutterError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: listResponse[2])))
      } else if listResponse[0] == nil {
        completion(.failure(FlutterError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: nil)))
      } else {
        let result = listResponse[0] as! String
        completion(.success(result))
      }
    }
  }
}
