// Autogenerated from Pigeon (https://pub.dev/packages/pigeon), do not edit
// directly.
//
// ⚠️ HAND-WRITTEN APPROXIMATION — see pigeons/gfmc_api.dart's header. No
// Dart/Flutter SDK was available when this was authored, so the real
// `dart run pigeon` was never run against the schema. Regenerate with:
//   dart run pigeon --input pigeons/gfmc_api.dart
// and diff before trusting this beyond a starting point.
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.sltr.gfmc.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> = listOf(result)

private fun wrapError(exception: Throwable): List<Any?> =
    listOf(exception.javaClass.simpleName, exception.message, exception.stackTraceToString())

enum class GfmcEnvMessage(val raw: Int) { PRODUCTION(0), SANDBOX(1), DEV(2) }

enum class GfmcThemeMessage(val raw: Int) { DARK(0), LIGHT(1), AUTO(2) }

enum class GfmcErrorMessage(val raw: Int) {
    AUTH_FAILED(0),
    NETWORK_ERROR(1),
    SESSION_EXPIRED(2),
    SDK_NOT_INITIALIZED(3),
    WEBVIEW_UNAVAILABLE(4),
    WEBVIEW_OUTDATED(5),
    WEBVIEW_RENDERER_GONE(6),
    BILLING_UNAVAILABLE(7),
    PURCHASE_FAILED(8),
    VERIFY_FAILED(9),
}

enum class GfmcModuleMessage(val raw: Int) { CINEMA(0), GAME(1), SHOP(2) }

data class GfmcConfigMessage(
    val environment: GfmcEnvMessage = GfmcEnvMessage.PRODUCTION,
    val locale: String = "en",
    val theme: GfmcThemeMessage = GfmcThemeMessage.AUTO,
    val enableLogging: Boolean = false,
    val connectionTimeoutMs: Long = 10000L,
) {
    companion object {
        fun fromList(list: List<Any?>): GfmcConfigMessage {
            return GfmcConfigMessage(
                environment = GfmcEnvMessage.values()[list[0] as Int],
                locale = list[1] as String,
                theme = GfmcThemeMessage.values()[list[2] as Int],
                enableLogging = list[3] as Boolean,
                connectionTimeoutMs = (list[4] as Number).toLong(),
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(environment.raw, locale, theme.raw, enableLogging, connectionTimeoutMs)
}

data class GfmcVersionMessage(
    val name: String,
    val versionCode: Long,
    val artifactVersion: String,
    val displayName: String,
) {
    companion object {
        fun fromList(list: List<Any?>): GfmcVersionMessage {
            return GfmcVersionMessage(
                name = list[0] as String,
                versionCode = (list[1] as Number).toLong(),
                artifactVersion = list[2] as String,
                displayName = list[3] as String,
            )
        }
    }

    fun toList(): List<Any?> = listOf(name, versionCode, artifactVersion, displayName)
}

private class PigeonCodec : StandardMessageCodec() {
    override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
        return when (type) {
            129.toByte() -> GfmcConfigMessage.fromList(readValue(buffer) as List<Any?>)
            130.toByte() -> GfmcVersionMessage.fromList(readValue(buffer) as List<Any?>)
            else -> super.readValueOfType(type, buffer)
        }
    }

    override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
        when (value) {
            is GfmcConfigMessage -> {
                stream.write(129)
                writeValue(stream, value.toList())
            }
            is GfmcVersionMessage -> {
                stream.write(130)
                writeValue(stream, value.toList())
            }
            else -> super.writeValue(stream, value)
        }
    }
}

val GfmcPigeonCodec: MessageCodec<Any?> by lazy { PigeonCodec() }

/**
 * Implement this on the Android side and call [GfmcHostApi.setUp] with the
 * instance — the plugin's GfmcFlutterPlugin does this, delegating each
 * method to the real com.sltr.gfmc.GfmcSDK.
 */
interface GfmcHostApi {
    fun init(config: GfmcConfigMessage)
    fun open(jwt: String)
    fun closeMiniApp()
    fun getVersion(): GfmcVersionMessage
    fun getConfig(): GfmcConfigMessage?

    companion object {
        const val CHANNEL_PREFIX = "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi."

        /** Sets up an instance of [GfmcHostApi] to handle messages from Dart. */
        fun setUp(binaryMessenger: BinaryMessenger, api: GfmcHostApi?, messageChannelSuffix: String = "") {
            val suffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
            run {
                val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}init$suffix", GfmcPigeonCodec)
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val wrapped: List<Any?> = try {
                            api.init(args[0] as GfmcConfigMessage)
                            wrapResult(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}open$suffix", GfmcPigeonCodec)
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val wrapped: List<Any?> = try {
                            api.open(args[0] as String)
                            wrapResult(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}closeMiniApp$suffix", GfmcPigeonCodec)
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> = try {
                            api.closeMiniApp()
                            wrapResult(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}getVersion$suffix", GfmcPigeonCodec)
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> = try {
                            wrapResult(api.getVersion())
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}getConfig$suffix", GfmcPigeonCodec)
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> = try {
                            wrapResult(api.getConfig())
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}

/**
 * Caller for the Dart-implemented [GfmcFlutterApi] — used by the plugin to
 * push events (hub ready/closed, purchase/error/module events) and to await
 * a fresh JWT from [refreshToken]. One instance per BinaryMessenger, built
 * once in GfmcFlutterPlugin.onAttachedToEngine and reused for the plugin's
 * lifetime.
 */
class GfmcFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
    companion object {
        private const val CHANNEL_PREFIX = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi."
        private const val TAG = "GfmcFlutterApi"
    }

    private val suffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""

    fun onHubReady(callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onHubReady$suffix", GfmcPigeonCodec)
        channel.send(emptyList<Any?>()) { callback(Result.success(Unit)) }
    }

    fun onHubClosed(callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onHubClosed$suffix", GfmcPigeonCodec)
        channel.send(emptyList<Any?>()) { callback(Result.success(Unit)) }
    }

    fun onError(code: GfmcErrorMessage, message: String, callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onError$suffix", GfmcPigeonCodec)
        channel.send(listOf(code.raw, message)) { callback(Result.success(Unit)) }
    }

    fun onPurchaseCompleted(sku: String, txId: String, callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onPurchaseCompleted$suffix", GfmcPigeonCodec)
        channel.send(listOf(sku, txId)) { callback(Result.success(Unit)) }
    }

    fun onPurchaseFailed(reason: String, callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onPurchaseFailed$suffix", GfmcPigeonCodec)
        channel.send(listOf(reason)) { callback(Result.success(Unit)) }
    }

    fun onModuleChanged(module: GfmcModuleMessage, callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onModuleChanged$suffix", GfmcPigeonCodec)
        channel.send(listOf(module.raw)) { callback(Result.success(Unit)) }
    }

    fun onShareRequested(url: String, title: String, callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onShareRequested$suffix", GfmcPigeonCodec)
        channel.send(listOf(url, title)) { callback(Result.success(Unit)) }
    }

    fun onSkuSelected(sku: String, callback: (Result<Unit>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}onSkuSelected$suffix", GfmcPigeonCodec)
        channel.send(listOf(sku)) { callback(Result.success(Unit)) }
    }

    /**
     * Awaits a fresh JWT from the Dart-side implementation. [callback]
     * receives `Result.success(jwt)` or `Result.failure(...)` — map the
     * latter to GfmcRefreshResult.fail(...) at the call site.
     */
    fun refreshToken(callback: (Result<String>) -> Unit) {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "${CHANNEL_PREFIX}refreshToken$suffix", GfmcPigeonCodec)
        channel.send(emptyList<Any?>()) { response ->
            val list = response as? List<Any?>
            when {
                list == null -> callback(Result.failure(RuntimeException("refreshToken: no response from Dart")))
                list.size >= 3 && list[0] is String && (list[0] as String).endsWith("-error") ->
                    callback(Result.failure(RuntimeException(list[1] as? String ?: "refresh failed")))
                list.isNotEmpty() && list[0] is String -> callback(Result.success(list[0] as String))
                else -> callback(Result.failure(RuntimeException("refreshToken: malformed response $list")))
            }
        }
    }
}
