// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.sltr.gfmc.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class GfmcEnvMessage(val raw: Int) {
  PRODUCTION(0),
  SANDBOX(1),
  DEV(2);

  companion object {
    fun ofRaw(raw: Int): GfmcEnvMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class GfmcThemeMessage(val raw: Int) {
  DARK(0),
  LIGHT(1),
  AUTO(2);

  companion object {
    fun ofRaw(raw: Int): GfmcThemeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class GfmcErrorMessage(val raw: Int) {
  AUTH_FAILED(0),
  NETWORK_ERROR(1),
  SESSION_EXPIRED(2),
  SDK_NOT_INITIALIZED(3),
  WEBVIEW_UNAVAILABLE(4),
  WEBVIEW_OUTDATED(5),
  WEBVIEW_RENDERER_GONE(6),
  BILLING_UNAVAILABLE(7),
  PURCHASE_FAILED(8),
  VERIFY_FAILED(9);

  companion object {
    fun ofRaw(raw: Int): GfmcErrorMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class GfmcModuleMessage(val raw: Int) {
  CINEMA(0),
  GAME(1),
  SHOP(2);

  companion object {
    fun ofRaw(raw: Int): GfmcModuleMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GfmcConfigMessage (
  val environment: GfmcEnvMessage,
  val locale: String,
  val theme: GfmcThemeMessage,
  val enableLogging: Boolean,
  val connectionTimeoutMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GfmcConfigMessage {
      val environment = pigeonVar_list[0] as GfmcEnvMessage
      val locale = pigeonVar_list[1] as String
      val theme = pigeonVar_list[2] as GfmcThemeMessage
      val enableLogging = pigeonVar_list[3] as Boolean
      val connectionTimeoutMs = pigeonVar_list[4] as Long
      return GfmcConfigMessage(environment, locale, theme, enableLogging, connectionTimeoutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      environment,
      locale,
      theme,
      enableLogging,
      connectionTimeoutMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GfmcVersionMessage (
  /**
   * Internal SDK semantic version, e.g. "2.3.6". NOT what a host app
   * should show a partner — see [artifactVersion].
   */
  val name: String,
  val versionCode: Long,
  /**
   * The Maven coordinate this plugin's Android dependency actually pins,
   * e.g. "1.2.6" — what GfmcSDK.getArtifactVersion()/GET_APP_VERSION report
   * on the native side. This is the number to show or log.
   */
  val artifactVersion: String,
  val displayName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GfmcVersionMessage {
      val name = pigeonVar_list[0] as String
      val versionCode = pigeonVar_list[1] as Long
      val artifactVersion = pigeonVar_list[2] as String
      val displayName = pigeonVar_list[3] as String
      return GfmcVersionMessage(name, versionCode, artifactVersion, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      versionCode,
      artifactVersion,
      displayName,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GfmcEnvMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GfmcThemeMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GfmcErrorMessage.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GfmcModuleMessage.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GfmcConfigMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GfmcVersionMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GfmcEnvMessage -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is GfmcThemeMessage -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is GfmcErrorMessage -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is GfmcModuleMessage -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is GfmcConfigMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is GfmcVersionMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GfmcHostApi {
  /**
   * Must be called once before [open]. Safe to call again to change config
   * (e.g. switching environment) as long as no hub is currently open.
   *
   * Named `initialize`, not `init` — `init` is a reserved word in Swift, and
   * Pigeon 22.7.4 emits it unescaped (`func init(...)`) in the generated
   * `GfmcHostApi` protocol, which fails to compile. Confirmed by actually
   * running `dart run pigeon` against this schema (see this repo's
   * `Messages.g.swift` header). The public Dart-facing name is unaffected —
   * `GfmcSdk.init()` in lib/src/gfmc_sdk.dart just calls `_host.initialize`
   * underneath.
   */
  fun initialize(config: GfmcConfigMessage)
  /**
   * Opens the hub with a minicinema session JWT obtained from your own
   * backend — NOT your app's own auth access token. Requires [initialize]
   * first and a token refresher registered on the Dart side (see
   * GfmcFlutterApi.refreshToken) if you expect long sessions.
   */
  fun open(jwt: String)
  /**
   * Native-side "close" — same effect as the user tapping the capsule's
   * close button. No-op if no hub is currently open.
   */
  fun closeMiniApp()
  fun getVersion(): GfmcVersionMessage
  /** Null if [initialize] hasn't been called yet. */
  fun getConfig(): GfmcConfigMessage?

  companion object {
    /** The codec used by GfmcHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `GfmcHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GfmcHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as GfmcConfigMessage
            val wrapped: List<Any?> = try {
              api.initialize(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jwtArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.open(jwtArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.closeMiniApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.closeMiniApp()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getVersion())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getConfig())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class GfmcFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by GfmcFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onHubReady(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubReady$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onHubClosed(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubClosed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(codeArg: GfmcErrorMessage, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPurchaseCompleted(skuArg: String, txIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseCompleted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(skuArg, txIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPurchaseFailed(reasonArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseFailed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(reasonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onModuleChanged(moduleArg: GfmcModuleMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onModuleChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(moduleArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onShareRequested(urlArg: String, titleArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onShareRequested$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(urlArg, titleArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Informational only — does not gate the Google Play billing flow, which
   * runs natively regardless of what this returns.
   */
  fun onSkuSelected(skuArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onSkuSelected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(skuArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Native asks Dart for a fresh minicinema JWT when the current one
   * expires. Implement this to call your own backend and return the new
   * token; throw (or let the Future fail) to signal a refresh failure —
   * the native side maps that to the same "refresh failed" outcome as
   * GfmcTokenRefresher.fail(reason) on the Android side.
   */
  fun refreshToken(callback: (Result<String>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.refreshToken$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as String
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
