// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum GfmcEnvMessage {
  production,
  sandbox,
  dev,
}

enum GfmcThemeMessage {
  dark,
  light,
  auto,
}

enum GfmcErrorMessage {
  authFailed,
  networkError,
  sessionExpired,
  sdkNotInitialized,
  webviewUnavailable,
  webviewOutdated,
  webviewRendererGone,
  billingUnavailable,
  purchaseFailed,
  verifyFailed,
}

enum GfmcModuleMessage {
  cinema,
  game,
  shop,
}

class GfmcConfigMessage {
  GfmcConfigMessage({
    this.environment = GfmcEnvMessage.production,
    this.locale = 'en',
    this.theme = GfmcThemeMessage.auto,
    this.enableLogging = false,
    this.connectionTimeoutMs = 10000,
  });

  GfmcEnvMessage environment;

  String locale;

  GfmcThemeMessage theme;

  bool enableLogging;

  int connectionTimeoutMs;

  Object encode() {
    return <Object?>[
      environment,
      locale,
      theme,
      enableLogging,
      connectionTimeoutMs,
    ];
  }

  static GfmcConfigMessage decode(Object result) {
    result as List<Object?>;
    return GfmcConfigMessage(
      environment: result[0]! as GfmcEnvMessage,
      locale: result[1]! as String,
      theme: result[2]! as GfmcThemeMessage,
      enableLogging: result[3]! as bool,
      connectionTimeoutMs: result[4]! as int,
    );
  }
}

class GfmcVersionMessage {
  GfmcVersionMessage({
    required this.name,
    required this.versionCode,
    required this.artifactVersion,
    required this.displayName,
  });

  /// Internal SDK semantic version, e.g. "2.3.6". NOT what a host app
  /// should show a partner — see [artifactVersion].
  String name;

  int versionCode;

  /// The Maven coordinate this plugin's Android dependency actually pins,
  /// e.g. "1.2.6" — what GfmcSDK.getArtifactVersion()/GET_APP_VERSION report
  /// on the native side. This is the number to show or log.
  String artifactVersion;

  String displayName;

  Object encode() {
    return <Object?>[
      name,
      versionCode,
      artifactVersion,
      displayName,
    ];
  }

  static GfmcVersionMessage decode(Object result) {
    result as List<Object?>;
    return GfmcVersionMessage(
      name: result[0]! as String,
      versionCode: result[1]! as int,
      artifactVersion: result[2]! as String,
      displayName: result[3]! as String,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is GfmcEnvMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is GfmcThemeMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is GfmcErrorMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is GfmcModuleMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is GfmcConfigMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GfmcVersionMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GfmcEnvMessage.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GfmcThemeMessage.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GfmcErrorMessage.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GfmcModuleMessage.values[value];
      case 133: 
        return GfmcConfigMessage.decode(readValue(buffer)!);
      case 134: 
        return GfmcVersionMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class GfmcHostApi {
  /// Constructor for [GfmcHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GfmcHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Must be called once before [open]. Safe to call again to change config
  /// (e.g. switching environment) as long as no hub is currently open.
  ///
  /// Named `initialize`, not `init` — `init` is a reserved word in Swift, and
  /// Pigeon 22.7.4 emits it unescaped (`func init(...)`) in the generated
  /// `GfmcHostApi` protocol, which fails to compile. Confirmed by actually
  /// running `dart run pigeon` against this schema (see this repo's
  /// `Messages.g.swift` header). The public Dart-facing name is unaffected —
  /// `GfmcSdk.init()` in lib/src/gfmc_sdk.dart just calls `_host.initialize`
  /// underneath.
  Future<void> initialize(GfmcConfigMessage config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Opens the hub with a minicinema session JWT obtained from your own
  /// backend — NOT your app's own auth access token. Requires [initialize]
  /// first and a token refresher registered on the Dart side (see
  /// GfmcFlutterApi.refreshToken) if you expect long sessions.
  Future<void> open(String jwt) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.open$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[jwt]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Native-side "close" — same effect as the user tapping the capsule's
  /// close button. No-op if no hub is currently open.
  Future<void> closeMiniApp() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.closeMiniApp$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<GfmcVersionMessage> getVersion() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getVersion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as GfmcVersionMessage?)!;
    }
  }

  /// Null if [initialize] hasn't been called yet.
  Future<GfmcConfigMessage?> getConfig() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getConfig$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as GfmcConfigMessage?);
    }
  }
}

abstract class GfmcFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onHubReady();

  void onHubClosed();

  void onError(GfmcErrorMessage code, String message);

  void onPurchaseCompleted(String sku, String txId);

  void onPurchaseFailed(String reason);

  void onModuleChanged(GfmcModuleMessage module);

  void onShareRequested(String url, String title);

  /// Informational only — does not gate the Google Play billing flow, which
  /// runs natively regardless of what this returns.
  void onSkuSelected(String sku);

  /// Native asks Dart for a fresh minicinema JWT when the current one
  /// expires. Implement this to call your own backend and return the new
  /// token; throw (or let the Future fail) to signal a refresh failure —
  /// the native side maps that to the same "refresh failed" outcome as
  /// GfmcTokenRefresher.fail(reason) on the Android side.
  Future<String> refreshToken();

  static void setUp(GfmcFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubReady$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onHubReady();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubClosed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onHubClosed();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final GfmcErrorMessage? arg_code = (args[0] as GfmcErrorMessage?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onError was null, expected non-null GfmcErrorMessage.');
          final String? arg_message = (args[1] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_code!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseCompleted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseCompleted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_sku = (args[0] as String?);
          assert(arg_sku != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseCompleted was null, expected non-null String.');
          final String? arg_txId = (args[1] as String?);
          assert(arg_txId != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseCompleted was null, expected non-null String.');
          try {
            api.onPurchaseCompleted(arg_sku!, arg_txId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseFailed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseFailed was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_reason = (args[0] as String?);
          assert(arg_reason != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseFailed was null, expected non-null String.');
          try {
            api.onPurchaseFailed(arg_reason!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onModuleChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onModuleChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final GfmcModuleMessage? arg_module = (args[0] as GfmcModuleMessage?);
          assert(arg_module != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onModuleChanged was null, expected non-null GfmcModuleMessage.');
          try {
            api.onModuleChanged(arg_module!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onShareRequested$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onShareRequested was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_url = (args[0] as String?);
          assert(arg_url != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onShareRequested was null, expected non-null String.');
          final String? arg_title = (args[1] as String?);
          assert(arg_title != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onShareRequested was null, expected non-null String.');
          try {
            api.onShareRequested(arg_url!, arg_title!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onSkuSelected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onSkuSelected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_sku = (args[0] as String?);
          assert(arg_sku != null,
              'Argument for dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onSkuSelected was null, expected non-null String.');
          try {
            api.onSkuSelected(arg_sku!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.refreshToken$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final String output = await api.refreshToken();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
