// Autogenerated from Pigeon (https://pub.dev/packages/pigeon), do not edit
// directly.
//
// ⚠️ HAND-WRITTEN APPROXIMATION — see pigeons/gfmc_api.dart's header. No
// Dart/Flutter SDK was available when this was authored, so the real
// `dart run pigeon` was never run against the schema. Regenerate with:
//   dart run pigeon --input pigeons/gfmc_api.dart
// and diff before trusting this beyond a starting point.
//
// ignore_for_file: public_member_api_docs, non_constant_identifier_names,
// avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators,
// omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

// -- Enums --------------------------------------------------------------

enum GfmcEnvMessage { production, sandbox, dev }

enum GfmcThemeMessage { dark, light, auto }

enum GfmcErrorMessage {
  authFailed,
  networkError,
  sessionExpired,
  sdkNotInitialized,
  webviewUnavailable,
  webviewOutdated,
  webviewRendererGone,
  billingUnavailable,
  purchaseFailed,
  verifyFailed,
}

enum GfmcModuleMessage { cinema, game, shop }

// -- Data classes ---------------------------------------------------------

class GfmcConfigMessage {
  GfmcConfigMessage({
    this.environment = GfmcEnvMessage.production,
    this.locale = 'en',
    this.theme = GfmcThemeMessage.auto,
    this.enableLogging = false,
    this.connectionTimeoutMs = 10000,
  });

  GfmcEnvMessage environment;
  String locale;
  GfmcThemeMessage theme;
  bool enableLogging;
  int connectionTimeoutMs;

  List<Object?> _toList() {
    return <Object?>[
      environment.index,
      locale,
      theme.index,
      enableLogging,
      connectionTimeoutMs,
    ];
  }

  static GfmcConfigMessage decode(Object result) {
    result as List<Object?>;
    return GfmcConfigMessage(
      environment: GfmcEnvMessage.values[result[0]! as int],
      locale: result[1]! as String,
      theme: GfmcThemeMessage.values[result[2]! as int],
      enableLogging: result[3]! as bool,
      connectionTimeoutMs: result[4]! as int,
    );
  }
}

class GfmcVersionMessage {
  GfmcVersionMessage({
    required this.name,
    required this.versionCode,
    required this.artifactVersion,
    required this.displayName,
  });

  String name;
  int versionCode;
  String artifactVersion;
  String displayName;

  List<Object?> _toList() {
    return <Object?>[name, versionCode, artifactVersion, displayName];
  }

  static GfmcVersionMessage decode(Object result) {
    result as List<Object?>;
    return GfmcVersionMessage(
      name: result[0]! as String,
      versionCode: result[1]! as int,
      artifactVersion: result[2]! as String,
      displayName: result[3]! as String,
    );
  }
}

// -- Codec ------------------------------------------------------------------

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is GfmcConfigMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value._toList());
    } else if (value is GfmcVersionMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value._toList());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return GfmcConfigMessage.decode(readValue(buffer)!);
      case 130:
        return GfmcVersionMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

// -- Host API (Dart -> native) -----------------------------------------------

class GfmcHostApi {
  /// Constructor for [GfmcHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection in tests; you shouldn't need it
  /// otherwise.
  GfmcHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();
  final String pigeonVar_messageChannelSuffix;

  Future<void> init(GfmcConfigMessage config) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.init$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> open(String jwt) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.open$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[jwt]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> closeMiniApp() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.closeMiniApp$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<GfmcVersionMessage> getVersion() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getVersion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as GfmcVersionMessage?)!;
    }
  }

  Future<GfmcConfigMessage?> getConfig() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.gfmc_flutter.GfmcHostApi.getConfig$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as GfmcConfigMessage?);
    }
  }
}

// -- Flutter API (native -> Dart) -------------------------------------------

abstract class GfmcFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onHubReady();

  void onHubClosed();

  void onError(GfmcErrorMessage code, String message);

  void onPurchaseCompleted(String sku, String txId);

  void onPurchaseFailed(String reason);

  void onModuleChanged(GfmcModuleMessage module);

  void onShareRequested(String url, String title);

  void onSkuSelected(String sku);

  /// Native awaits this Future — implement it to call your backend and
  /// return the fresh JWT, or throw to signal a refresh failure.
  Future<String> refreshToken();

  static void setUp(
    GfmcFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubReady$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          api.onHubReady();
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onHubClosed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          api.onHubClosed();
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onError$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>?)!;
          final GfmcErrorMessage? arg_code = (args[0] as int?) == null
              ? null
              : GfmcErrorMessage.values[args[0]! as int];
          final String? arg_message = (args[1] as String?);
          api.onError(arg_code!, arg_message!);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseCompleted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_sku = (args[0] as String?);
          final String? arg_txId = (args[1] as String?);
          api.onPurchaseCompleted(arg_sku!, arg_txId!);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onPurchaseFailed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_reason = (args[0] as String?);
          api.onPurchaseFailed(arg_reason!);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onModuleChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>?)!;
          final GfmcModuleMessage? arg_module = (args[0] as int?) == null
              ? null
              : GfmcModuleMessage.values[args[0]! as int];
          api.onModuleChanged(arg_module!);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onShareRequested$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_url = (args[0] as String?);
          final String? arg_title = (args[1] as String?);
          api.onShareRequested(arg_url!, arg_title!);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.onSkuSelected$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_sku = (args[0] as String?);
          api.onSkuSelected(arg_sku!);
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gfmc_flutter.GfmcFlutterApi.refreshToken$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final String output = await api.refreshToken();
            return <Object?>[output];
          } catch (e) {
            return <Object?>[
              'refresh-error',
              e.toString(),
              null,
            ];
          }
        });
      }
    }
  }
}
